services:
  - type: web
    name: calorie-api
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: USDA_API_KEY
        sync: false
    pythonVersion: 3.10.12
